CP-13294: Fix compilation on CentOS 7.1
The new multiboot 2 code fails to build with:
  Error: non-empty .rodata: 0x01c
unless -fno-jump-tables is used.