Fix build issue in VBD3 stats
Move the _GNU_SOURCE defintion ahead of all includes.  Currently, it fails to
include a definition for asprintf()

  src/xenstat_linux.c: In function 'xenstat_collect_vbds':
  src/xenstat_linux.c:522:4: warning: implicit declaration of function 'asprintf' [-Wimplicit-function-declaration]
      if (asprintf(&path, "/local/domain/0/backend/vbd3/%u/%u/kthread-pid", domid, vbd.dev) < 0)
      ^

This is fatal in Xen 4.13 when -Werror is used on libxenstat.

Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>